#!/bin/bash

# Жестко прописываем путь, если переменная не подхватывается
HWL_SCRIPT="/home/devLogger/.config/hwlang/hwl.py"

if [ -z "$1" ]; then
    echo "Ошибка: не указан файл"
    exit 1
fi

# Явно вызываем Python3 и твой интерпретатор
python3 "$HWL_SCRIPT" "$1"